version: "3"
services:
  apache:
    build:
      context: ./dockerfiles/apache
    volumes:
      - "./:/var/www/htdocs"
      - "./dockerfiles/apache/confs:/usr/local/apache2/conf/custom.conf.d"
    ports:
      - "80:80"
    depends_on:
      - php
  php:
    build:
      context: ./dockerfiles/php
    volumes:
      - "./:/var/www/htdocs"
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - MYSQL_USER
      - MYSQL_PASS
      - MYSQL_DATABASE
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 9001:80

volumes:
  mysql_data:
networks:
  default:
    driver: bridge